[[news]]
date = "2025-11"
content = "Begin my Internship in Shanghai AI Lab."

[[news]]
date = "2025-07"
content = "Starting my Research Internship at NC State University."

[[news]]
date = "2025-06"
content = "Our first work has been accepted by Conf-MLA.ðŸŽ‰"
